Repository shaka-project/karma-local-wd-launcher, pull requests merged in 2025-02, with the labels that each got.

#84 fix: Log webdrivers installation in debug mode
  index.js
Labels: type: bug, priority: P3

#86 fix: Improve error resiliency of drivers installation
  index.js
  package-lock.json
  package.json
Labels: type: bug, priority: P1

#88 feat: Force to enable Widevine on Firefox
  index.js
Labels: type: enhancement, browser: Firefox
